"""The checked-in wire fixture, and the gate that stops it drifting.

A separate lane builds the browser half against this file, in another repo. A
hand-typed sample would be a helper describing a wire no server writes -- which
has already made this family's tests agree with a bug more than once -- so the
file is generated by driving the real endpoint, and regenerated here on every
run. Any difference between what the server emits and what is checked in fails,
in whichever direction it moved.
"""

from __future__ import annotations

import json
import os
import pathlib
import subprocess
import sys
from typing import Any

REPO_ROOT = pathlib.Path(__file__).resolve().parents[2]
GENERATOR = REPO_ROOT / "scripts" / "generate_subagent_fixture.py"
FIXTURE = REPO_ROOT / "tests" / "fixtures" / "subagent_progress_stream.json"


def _document() -> dict[str, Any]:
    return json.loads(FIXTURE.read_text())


def _progress() -> list[dict[str, Any]]:
    return [
        event["value"]
        for event in _document()["events"]
        if event["type"] == "CUSTOM" and event["name"] == "ag_ui.subagent"
    ]


def test_regenerating_the_fixture_changes_nothing(tmp_path: pathlib.Path) -> None:
    regenerated = tmp_path / "regenerated.json"
    # The generator configures its own settings, so the suite's are taken out of
    # its way: the fixture describes the shipped endpoint, not this test module's
    # environment.
    env = {key: value for key, value in os.environ.items() if key != "DJANGO_SETTINGS_MODULE"}

    subprocess.run(
        [sys.executable, str(GENERATOR), str(regenerated)],
        check=True,
        cwd=REPO_ROOT,
        env=env,
        capture_output=True,
    )

    assert regenerated.read_bytes() == FIXTURE.read_bytes()


def test_the_fixture_covers_every_phase_of_the_contract() -> None:
    # What the browser lane is entitled to find in it. A scenario that stopped
    # exercising a phase would leave that half of the contract undemonstrated.
    assert {value["phase"] for value in _progress()} == {
        "started",
        "tool_call",
        "tool_result",
        "finished",
        "failed",
    }


def test_the_fixture_shows_both_tool_outcomes() -> None:
    outcomes = {value["tool"]["ok"] for value in _progress() if "tool" in value}

    assert outcomes == {None, True, False}


def test_every_delegation_opens_once_and_closes_once() -> None:
    opened: dict[str, list[str]] = {}
    for value in _progress():
        opened.setdefault(value["delegationId"], []).append(value["phase"])

    for phases in opened.values():
        assert phases[0] == "started"
        assert phases[-1] in {"finished", "failed"}
        assert phases.count("started") == 1
        assert sum(phase in {"finished", "failed"} for phase in phases) == 1


def test_a_delegation_is_keyed_to_a_tool_call_the_client_already_saw() -> None:
    announced = {value["delegationId"] for value in _progress()}
    drawn = {
        event["toolCallId"] for event in _document()["events"] if event["type"] == "TOOL_CALL_START"
    }

    assert announced <= drawn


def test_the_failure_detail_rides_the_tool_result_and_not_the_progress() -> None:
    # The split the contract turns on. The progress channel names the sub-agent
    # and stops; the words the model was given travel the ordinary tool result,
    # which the client renders on the card this progress belongs to.
    failed = [value for value in _progress() if value["phase"] == "failed"]
    results = [
        event["content"] for event in _document()["events"] if event["type"] == "TOOL_CALL_RESULT"
    ]

    assert failed == [
        {
            "delegationId": "call-2",
            "agent": "auditor",
            "phase": "failed",
            "status": "auditor failed",
        }
    ]
    assert any("the auditor model went away" in content for content in results)
