# Generated by Django 5.2.14 on 2026-06-24 09:58

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="StoredConversation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("thread_id", models.CharField(max_length=255)),
                ("owner_id", models.CharField(blank=True, default="", max_length=255)),
                ("title", models.CharField(blank=True, default="", max_length=255)),
                ("preview", models.TextField(blank=True, default="")),
                ("messages", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["owner_id", "-updated_at"],
                        name="django_ag_u_owner_i_ce0436_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("owner_id", "thread_id"),
                        name="django_ag_ui_store_owner_thread_unique",
                    )
                ],
            },
        ),
    ]
