# Generated by Django 5.2.14 on 2026-06-25 04:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_ag_ui_store", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="StoredAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("attachment_id", models.CharField(max_length=255)),
                ("owner_id", models.CharField(blank=True, default="", max_length=255)),
                ("thread_id", models.CharField(blank=True, default="", max_length=255)),
                ("name", models.CharField(blank=True, default="", max_length=255)),
                ("mime", models.CharField(blank=True, default="", max_length=255)),
                ("size", models.PositiveBigIntegerField(default=0)),
                ("file", models.FileField(upload_to="django_ag_ui/attachments/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["owner_id", "-created_at"],
                        name="django_ag_u_owner_i_56e23e_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("owner_id", "attachment_id"),
                        name="django_ag_ui_attachment_owner_id_unique",
                    )
                ],
            },
        ),
    ]
