# Generated by Django 5.2.16 on 2026-07-22 09:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_ag_ui_store", "0002_storedattachment"),
    ]

    operations = [
        migrations.CreateModel(
            name="StoredRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("run_id", models.CharField(max_length=255)),
                ("owner_id", models.CharField(blank=True, default="", max_length=255)),
                (
                    "conversation_id",
                    models.CharField(blank=True, default=None, max_length=255, null=True),
                ),
                (
                    "parent_run_id",
                    models.CharField(blank=True, default=None, max_length=255, null=True),
                ),
                (
                    "agent_name",
                    models.CharField(blank=True, default=None, max_length=255, null=True),
                ),
                ("metadata", models.JSONField(default=dict)),
                ("started_at", models.DateTimeField()),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["owner_id", "started_at"],
                        name="django_ag_u_owner_i_76f7b1_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("owner_id", "run_id"),
                        name="django_ag_ui_run_owner_run_unique",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="StoredSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("run_id", models.CharField(max_length=255)),
                ("owner_id", models.CharField(blank=True, default="", max_length=255)),
                ("step_index", models.IntegerField()),
                ("messages", models.JSONField(default=list)),
                (
                    "conversation_id",
                    models.CharField(blank=True, default=None, max_length=255, null=True),
                ),
                (
                    "parent_run_id",
                    models.CharField(blank=True, default=None, max_length=255, null=True),
                ),
                (
                    "agent_name",
                    models.CharField(blank=True, default=None, max_length=255, null=True),
                ),
                ("timestamp", models.DateTimeField()),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["owner_id", "run_id"],
                        name="django_ag_u_owner_i_a6e4af_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="StoredStepEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("run_id", models.CharField(max_length=255)),
                ("owner_id", models.CharField(blank=True, default="", max_length=255)),
                ("kind", models.CharField(max_length=32)),
                ("step_index", models.IntegerField()),
                ("timestamp", models.DateTimeField()),
                (
                    "conversation_id",
                    models.CharField(blank=True, default=None, max_length=255, null=True),
                ),
                (
                    "parent_run_id",
                    models.CharField(blank=True, default=None, max_length=255, null=True),
                ),
                (
                    "agent_name",
                    models.CharField(blank=True, default=None, max_length=255, null=True),
                ),
                (
                    "tool_call_id",
                    models.CharField(blank=True, default=None, max_length=255, null=True),
                ),
                (
                    "tool_name",
                    models.CharField(blank=True, default=None, max_length=255, null=True),
                ),
                ("error", models.TextField(blank=True, default=None, null=True)),
                ("metadata", models.JSONField(default=dict)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["owner_id", "run_id"],
                        name="django_ag_u_owner_i_8fc39a_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="StoredToolEffect",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("run_id", models.CharField(max_length=255)),
                ("owner_id", models.CharField(blank=True, default="", max_length=255)),
                ("tool_call_id", models.CharField(max_length=255)),
                ("tool_name", models.CharField(max_length=255)),
                ("status", models.CharField(max_length=16)),
                ("started_at", models.DateTimeField()),
                ("ended_at", models.DateTimeField(blank=True, default=None, null=True)),
                (
                    "idempotency_key",
                    models.CharField(blank=True, default=None, max_length=255, null=True),
                ),
                (
                    "effect_summary",
                    models.TextField(blank=True, default=None, null=True),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["owner_id", "run_id"],
                        name="django_ag_u_owner_i_bf4e7a_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("owner_id", "run_id", "tool_call_id"),
                        name="django_ag_ui_tool_effect_owner_run_call_unique",
                    )
                ],
            },
        ),
    ]
